import type { EquipmentDataset } from './equipment-types'

export const MAGUS_EQUIPMENT_DATA: EquipmentDataset = {
  source: {
    file: 'rules/fegyverek.md',
    pages: { from: 'page_0198.txt', to: 'page_0216.txt' },
    language: 'hu',
    ocrNormalized: true,
  },
  weapons: [
    // 1. meretkategoria
    {
      name: 'Pusztakezes harc',
      kind: 'kozelharci',
      category: 1,
      subgroup: '1. meretkategoria',
      time: 3,
      damage: 'kepzettseg szerint',
      ke: null,
      te: null,
      ve: null,
      ce: null,
      rangeFeet: null,
      weight: null,
      price: null,
      disarm: 'igen',
      weaponBreak: 'nem',
      penetration: 'nem',
      stp: null,
    },
    {
      name: 'Vasokol',
      kind: 'kozelharci',
      category: 1,
      subgroup: '1. meretkategoria',
      time: 5,
      damage: '1k10',
      ke: null,
      te: null,
      ve: null,
      ce: null,
      rangeFeet: null,
      weight: 0.4,
      price: '1e',
      disarm: 'nem',
      weaponBreak: 'nem',
      penetration: 'nem',
      stp: 10,
    },

    // 2. meretkategoria (tor jellegu)
    { name: 'Beltepo', kind: 'kozelharci', category: 2, subgroup: 'Tor jellegu', time: 3, damage: '1k10', ke: 4, te: 9, ve: 2, ce: null, rangeFeet: null, weight: 0.5, price: '5e', disarm: 'nem', weaponBreak: 'nem', penetration: 'nem', stp: 15 },
    { name: 'Dzsambia', kind: 'kozelharci', category: 2, subgroup: 'Tor jellegu', time: 3, damage: '1k10', ke: 6, te: 12, ve: 2, ce: null, rangeFeet: null, weight: 0.4, price: '1a5e', disarm: 'nem', weaponBreak: 'nem', penetration: 'nem', stp: 10 },
    { name: 'Kes', kind: 'kozelharci', category: 2, subgroup: 'Tor jellegu', time: 3, damage: '1k6', ke: 5, te: 8, ve: 2, ce: null, rangeFeet: null, weight: 0.3, price: '50r', disarm: 'nem', weaponBreak: 'nem', penetration: 'nem', stp: 15 },
    { name: 'Leveltor', kind: 'kozelharci', category: 2, subgroup: 'Tor jellegu', time: 2, damage: '1k6+1', ke: 8, te: 10, ve: 5, ce: null, rangeFeet: null, weight: 0.3, price: '2a', disarm: 'nem', weaponBreak: 'nem', penetration: 'nem', stp: 10 },
    { name: 'Meregfog', kind: 'kozelharci', category: 2, subgroup: 'Tor jellegu', time: 3, damage: '1k6', ke: 5, te: 8, ve: 2, ce: null, rangeFeet: null, weight: 0.2, price: '2a', disarm: 'nem', weaponBreak: 'nem', penetration: 'nem', stp: 20 },
    { name: 'Pugoss', kind: 'kozelharci', category: 2, subgroup: 'Tor jellegu', time: 5, damage: '1k10', ke: 6, te: 10, ve: 3, ce: null, rangeFeet: null, weight: 0.5, price: '1a', disarm: 'nem', weaponBreak: 'nem', penetration: 'nem', stp: 10 },
    { name: 'Ramiera', kind: 'kozelharci', category: 2, subgroup: 'Tor jellegu', time: 3, damage: '1k6+2', ke: 6, te: 10, ve: 5, ce: null, rangeFeet: null, weight: 0.4, price: '2a', disarm: 'nem', weaponBreak: 'nem', penetration: 'nem', stp: 10 },
    { name: 'Tor', kind: 'kozelharci', category: 2, subgroup: 'Tor jellegu', time: 3, damage: '1k10', ke: 6, te: 10, ve: 4, ce: null, rangeFeet: null, weight: 0.5, price: '1e', disarm: 'nem', weaponBreak: 'nem', penetration: 'nem', stp: 10 },

    // 3. meretkategoria (egykezes kardok)
    { name: 'Dzsenn szablya', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 5, damage: '1k10+1', ke: 6, te: 14, ve: 14, ce: null, rangeFeet: null, weight: 1.0, price: '100a', disarm: 'igen', weaponBreak: 'nem', penetration: 'nem', stp: 30, notes: ['magikus'] },
    { name: 'Emrelin kard', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 5, damage: '1k10+1', ke: 5, te: 12, ve: 12, ce: null, rangeFeet: null, weight: 1.3, price: '2a', disarm: 'igen', weaponBreak: 'nem', penetration: 'nem', stp: 20 },
    { name: 'Fejvadaszkard', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 5, damage: '1k10', ke: 6, te: 14, ve: 10, ce: null, rangeFeet: null, weight: 0.8, price: '2a', disarm: 'nem', weaponBreak: 'nem', penetration: 'nem', stp: 20 },
    { name: 'Haritotor', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 3, damage: '1k6+1', ke: 5, te: 8, ve: 20, ce: null, rangeFeet: null, weight: 1.0, price: '2a', disarm: 'igen', weaponBreak: 'igen', penetration: 'nem', stp: 20 },
    { name: 'Hieguar', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 5, damage: '1k10+1', ke: 6, te: 14, ve: 8, ce: null, rangeFeet: null, weight: 1.0, price: '50a', disarm: 'nem', weaponBreak: 'nem', penetration: 'nem', stp: 20 },
    { name: 'Hosszu kard', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 5, damage: '2k6', ke: 5, te: 10, ve: 10, ce: null, rangeFeet: null, weight: 1.5, price: '1a5e', disarm: 'igen', weaponBreak: 'igen', penetration: 'nem', stp: 20 },
    { name: 'Jatagan', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 5, damage: '1k6+2', ke: 9, te: 14, ve: 8, ce: null, rangeFeet: null, weight: 0.9, price: '3a', disarm: 'igen', weaponBreak: 'igen', penetration: 'nem', stp: 20 },
    { name: 'Khossas', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 5, damage: '1k10+1', ke: 6, te: 14, ve: 3, ce: null, rangeFeet: null, weight: 0.7, price: '15a', disarm: 'nem', weaponBreak: 'nem', penetration: 'nem', stp: 20 },
    { name: 'Kigyokard', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 5, damage: '1k10+1', ke: 6, te: 15, ve: 10, ce: null, rangeFeet: null, weight: 1.6, price: '2a', disarm: 'igen', weaponBreak: 'igen', penetration: 'nem', stp: 20 },
    { name: 'Lagoss', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 5, damage: '1k10+1', ke: 8, te: 15, ve: 3, ce: null, rangeFeet: null, weight: 1.0, price: '1a', disarm: 'nem', weaponBreak: 'nem', penetration: 'nem', stp: 20 },
    { name: 'Meneth', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 5, damage: '2k6+1', ke: 1, te: 10, ve: 8, ce: null, rangeFeet: null, weight: 2.2, price: '15a', disarm: 'igen', weaponBreak: 'igen', penetration: 'nem', stp: 25 },
    { name: 'Mesterkard', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 5, damage: '2k6', ke: 5, te: 13, ve: 7, ce: null, rangeFeet: null, weight: 1.2, price: '3a', disarm: 'nem', weaponBreak: 'nem', penetration: 'nem', stp: 20 },
    { name: 'Predoci egyeneskard', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 5, damage: '1k10+2', ke: 5, te: 11, ve: 10, ce: null, rangeFeet: null, weight: 1.2, price: '1a5e', disarm: 'igen', weaponBreak: 'igen', penetration: 'nem', stp: 20 },
    { name: 'Rapir', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 3, damage: '1k10', ke: 7, te: 10, ve: 13, ce: null, rangeFeet: null, weight: 0.8, price: '5a', disarm: 'igen', weaponBreak: 'nem', penetration: 'nem', stp: 20 },
    { name: 'Rovid kard', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 5, damage: '1k10+1', ke: 5, te: 10, ve: 8, ce: null, rangeFeet: null, weight: 1.0, price: '1a', disarm: 'nem', weaponBreak: 'igen', penetration: 'igen', stp: 25 },
    { name: 'Seguor', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 5, damage: '1k6+2', ke: 5, te: 13, ve: 13, ce: null, rangeFeet: null, weight: 0.8, price: '1a3e', disarm: 'nem', weaponBreak: 'nem', penetration: 'nem', stp: 20 },
    { name: 'Slan kard', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 8, damage: '1k10+2', ke: 6, te: 18, ve: 12, ce: null, rangeFeet: null, weight: 1.6, price: '100a', disarm: 'igen*', weaponBreak: 'igen*', penetration: 'igen*', stp: 30, notes: ['magikus'] },
    { name: 'Slan tor', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 3, damage: '1k10', ke: 8, te: 14, ve: 8, ce: null, rangeFeet: null, weight: 0.9, price: '30a', disarm: 'igen*', weaponBreak: 'igen*', penetration: 'igen*', stp: 20, notes: ['magikus'] },
    { name: 'Szablya', kind: 'kozelharci', category: 3, subgroup: 'Egykezes kardok', time: 5, damage: '1k10+1', ke: 6, te: 10, ve: 12, ce: null, rangeFeet: null, weight: 1.2, price: '3a', disarm: 'igen', weaponBreak: 'nem', penetration: 'nem', stp: 20 },

    // 4. meretkategoria
    { name: 'Egykezes csatabard', kind: 'kozelharci', category: 4, subgroup: 'Csatabardok', time: 5, damage: '2k6+1', ke: 3, te: 10, ve: 5, ce: null, rangeFeet: null, weight: 1, price: '6e', disarm: 'igen', weaponBreak: 'igen', penetration: 'igen', stp: 25 },
    { name: 'Csatacsillag (csatabard)', kind: 'kozelharci', category: 4, subgroup: 'Csatabardok', time: 8, damage: '2k6+2', ke: 4, te: 13, ve: 4, ce: null, rangeFeet: null, weight: 2.2, price: '2a', disarm: 'igen', weaponBreak: 'nem', penetration: 'igen', stp: 20 },
    { name: 'Csatacsakany', kind: 'kozelharci', category: 4, subgroup: 'Csatabardok', time: 5, damage: '2k6+3', ke: 3, te: 11, ve: 5, ce: null, rangeFeet: null, weight: 2, price: '8e', disarm: 'igen', weaponBreak: 'nem', penetration: 'igen', stp: 20 },
    { name: 'Egykezes buzogany', kind: 'kozelharci', category: 4, subgroup: 'Buzoganyok', time: 5, damage: '2k6', ke: 5, te: 10, ve: 8, ce: null, rangeFeet: null, weight: 1.3, price: '1e', disarm: 'igen', weaponBreak: 'igen', penetration: 'igen', stp: 25 },
    { name: 'Harci kalapacs', kind: 'kozelharci', category: 4, subgroup: 'Buzoganyok', time: 5, damage: '2k6+1', ke: 2, te: 11, ve: 5, ce: null, rangeFeet: null, weight: 1.5, price: '1a', disarm: 'igen', weaponBreak: 'igen', penetration: 'igen', stp: 25 },
    { name: 'Shadleki buzogany', kind: 'kozelharci', category: 4, subgroup: 'Buzoganyok', time: 5, damage: '2k6', ke: 5, te: 13, ve: 7, ce: null, rangeFeet: null, weight: 2, price: '1a', disarm: 'igen', weaponBreak: 'igen', penetration: 'igen', stp: 20 },
    { name: 'Csatacsillag (buzogany)', kind: 'kozelharci', category: 4, subgroup: 'Buzoganyok', time: 5, damage: '2k6', ke: 6, te: 13, ve: 6, ce: null, rangeFeet: null, weight: 1.5, price: '1a2e', disarm: 'igen', weaponBreak: 'igen', penetration: 'igen', stp: 20 },
    { name: 'Furkosbot', kind: 'kozelharci', category: 4, subgroup: 'Botok', time: 5, damage: '1k10', ke: 5, te: 10, ve: 10, ce: null, rangeFeet: null, weight: 1, price: null, disarm: null, weaponBreak: null, penetration: null, stp: 10 },
    { name: 'Rovid bot', kind: 'kozelharci', category: 4, subgroup: 'Botok', time: 5, damage: '1k6+2', ke: 8, te: 12, ve: 12, ce: null, rangeFeet: null, weight: 1.1, price: '30r', disarm: 'igen*', weaponBreak: 'igen*', penetration: 'igen*', stp: 20 },
    { name: 'Lovagkard', kind: 'kozelharci', category: 4, subgroup: 'Nehezkardok', time: 5, damage: '3k6', ke: 3, te: 12, ve: 15, ce: null, rangeFeet: null, weight: 2, price: '3a', disarm: 'igen', weaponBreak: 'igen', penetration: 'igen', stp: 30 },
    { name: 'Masfelkezes kard', kind: 'kozelharci', category: 4, subgroup: 'Nehezkardok', time: 5, damage: '3k6', ke: 4, te: 15, ve: 11, ce: null, rangeFeet: null, weight: 2.5, price: '2a', disarm: 'igen', weaponBreak: 'igen', penetration: 'igen', stp: 30 },
    { name: 'Ketkezes kard', kind: 'kozelharci', category: 4, subgroup: 'Nehezkardok', time: 10, damage: '4k6+2', ke: 2, te: 16, ve: 8, ce: null, rangeFeet: null, weight: 4, price: '5a', disarm: 'nem', weaponBreak: 'igen', penetration: 'igen', stp: 25 },
    { name: 'Mara-seguor', kind: 'kozelharci', category: 4, subgroup: 'Nehezkardok', time: 5, damage: '3k6', ke: 7, te: 16, ve: 12, ce: null, rangeFeet: null, weight: 2.2, price: '2a', disarm: 'igen', weaponBreak: 'igen', penetration: 'igen', stp: 25 },
    { name: 'Slan csatakard', kind: 'kozelharci', category: 4, subgroup: 'Nehezkardok', time: 9, damage: '3k6', ke: 7, te: 15, ve: 8, ce: null, rangeFeet: null, weight: 2, price: '20a', disarm: 'igen', weaponBreak: 'igen', penetration: 'igen', stp: 40 },
    { name: 'Ketkezes csatabard', kind: 'kozelharci', category: 4, subgroup: 'Nehez csatabard', time: 10, damage: '5k6', ke: 0, te: 15, ve: 5, ce: null, rangeFeet: null, weight: 5, price: '2a', disarm: 'nem', weaponBreak: 'igen', penetration: 'igen', stp: 30 },
    { name: 'Ketkezes buzogany', kind: 'kozelharci', category: 4, subgroup: 'Buzoganyok', time: 10, damage: '3k6', ke: 0, te: 16, ve: 5, ce: null, rangeFeet: null, weight: 2, price: '1a2e', disarm: 'nem', weaponBreak: 'nem', penetration: 'igen', stp: 39 },
    { name: 'Lancos buzogany', kind: 'kozelharci', category: 4, subgroup: 'Buzoganyok', time: 5, damage: '2k6+1', ke: 5, te: 18, ve: 10, ce: null, rangeFeet: null, weight: 2, price: '6e', disarm: 'igen', weaponBreak: 'nem', penetration: 'nem', stp: 30 },
    { name: 'Hosszu bot', kind: 'kozelharci', category: 4, subgroup: 'Botok', time: 5, damage: '2k6', ke: 9, te: 10, ve: 16, ce: null, rangeFeet: null, weight: 2, price: '50r', disarm: 'igen*', weaponBreak: 'igen*', penetration: 'nem', stp: 30 },

    // 5. meretkategoria (nyeles)
    { name: 'Alabard', kind: 'kozelharci', category: 5, subgroup: 'Nyeles fegyverek', time: 10, damage: '5k6', ke: 10, te: 15, ve: 15, ce: null, rangeFeet: null, weight: 4, price: '8a', disarm: 'igen', weaponBreak: 'igen', penetration: 'igen', stp: 30 },
    { name: 'Landzsa', kind: 'kozelharci', category: 5, subgroup: 'Nyeles fegyverek', time: 5, damage: '2k6+2', ke: 13, te: 15, ve: 13, ce: null, rangeFeet: null, weight: 2.3, price: '8e', disarm: 'igen', weaponBreak: 'nem', penetration: 'igen', stp: 40 },
    { name: 'Lovaskopja', kind: 'kozelharci', category: 5, subgroup: 'Nyeles fegyverek', time: 'roham', damage: '4k6', ke: 15, te: 20, ve: 1, ce: null, rangeFeet: null, weight: 3, price: '1a', disarm: 'nem', weaponBreak: 'nem', penetration: 'igen', stp: 40 },
    { name: 'Nehezlovas kopja', kind: 'kozelharci', category: 5, subgroup: 'Nyeles fegyverek', time: 'roham', damage: '5k6', ke: 15, te: 19, ve: 1, ce: null, rangeFeet: null, weight: 5.5, price: '1a5e', disarm: 'nem', weaponBreak: 'nem', penetration: 'igen', stp: 35 },
    { name: 'Pika', kind: 'kozelharci', category: 5, subgroup: 'Nyeles fegyverek', time: 8, damage: '3k6+2', ke: 10, te: 14, ve: 12, ce: null, rangeFeet: null, weight: 2, price: '4e', disarm: 'nem', weaponBreak: 'nem', penetration: 'igen', stp: 40 },
    { name: 'Szigony', kind: 'kozelharci', category: 5, subgroup: 'Nyeles fegyverek', time: 5, damage: '3k6+1', ke: 8, te: 14, ve: 16, ce: null, rangeFeet: null, weight: 2.2, price: '5e', disarm: 'igen', weaponBreak: 'igen', penetration: 'igen', stp: 40 },

    // Hajitofegyverek
    { name: 'Bola', kind: 'hajitofegyver', subgroup: 'Hajitofegyverek', time: 5, damage: '1k6', ke: 2, te: null, ve: null, ce: 0, rangeFeet: 20, weight: 1, price: '40r', disarm: 'nem', weaponBreak: null, penetration: 'nem', stp: 10 },
    { name: 'Dobohalo', kind: 'hajitofegyver', subgroup: 'Hajitofegyverek', time: 10, damage: '-', ke: null, te: null, ve: 8, ce: 1, rangeFeet: 5, weight: 4, price: '3e', disarm: 'nem', weaponBreak: null, penetration: 'nem', stp: 10 },
    { name: 'Dobotor', kind: 'hajitofegyver', subgroup: 'Hajitofegyverek', time: 3, damage: '1k6', ke: 10, te: null, ve: 2, ce: 5, rangeFeet: 20, weight: 0.5, price: '6e', disarm: 'nem', weaponBreak: null, penetration: 'nem', stp: 10 },
    { name: 'Hajitobard', kind: 'hajitofegyver', subgroup: 'Hajitofegyverek', time: 3, damage: '1k6+2', ke: 9, te: null, ve: 4, ce: 6, rangeFeet: 20, weight: 1.2, price: '1e', disarm: 'nem', weaponBreak: null, penetration: 'nem', stp: 20 },
    { name: 'Hajitodarda', kind: 'hajitofegyver', subgroup: 'Hajitofegyverek', time: 5, damage: '2k6+1', ke: 8, te: null, ve: 5, ce: 13, rangeFeet: 50, weight: 1, price: '5e', disarm: 'nem', weaponBreak: null, penetration: 'igen', stp: 20 },
    { name: 'Slan csillag', kind: 'hajitofegyver', subgroup: 'Hajitofegyverek', time: 4, damage: '1k6/2', ke: 10, te: null, ve: null, ce: 4, rangeFeet: 40, weight: 0.1, price: '40r', disarm: 'nem', weaponBreak: null, penetration: 'nem', stp: 5 },

    // Ijak
    { name: 'Rovid ij', kind: 'ij', subgroup: 'Ijak', time: 2, damage: '1k6', ke: 5, te: null, ve: null, ce: 5, rangeFeet: 50, weight: 0.5, price: '2a', disarm: 'nem', weaponBreak: null, penetration: 'nem', stp: 9 },
    { name: 'Hosszu ij', kind: 'ij', subgroup: 'Ijak', time: 5, damage: '2k6+1', ke: 4, te: null, ve: null, ce: 4, rangeFeet: 150, weight: 1, price: '3a5e', disarm: 'nem', weaponBreak: null, penetration: 'nem', stp: 15 },
    { name: 'Visszacsapo ij', kind: 'ij', subgroup: 'Ijak', time: 3, damage: '2k6+2', ke: 3, te: null, ve: null, ce: 8, rangeFeet: 150, weight: 1, price: '25a', disarm: 'nem', weaponBreak: null, penetration: 'nem', stp: 25 },
    { name: 'Elf ij', kind: 'ij', subgroup: 'Ijak', time: 3, damage: '2k6+2 / 2k6', ke: null, te: null, ve: null, ce: null, rangeFeet: null, weight: 0.7, price: '120a', disarm: 'nem', weaponBreak: null, penetration: 'igen', stp: 30, notes: ['KET/CE/Tav kettos ertek: KE 6/4, CE 15/8, Tav 150/100'] },

    // Nyilpuskak
    { name: 'Konnyu nyilpuska', kind: 'nyilpuska', subgroup: 'Nyilpuskak', time: 3, damage: '1k6', ke: 5, te: null, ve: null, ce: 8, rangeFeet: 100, weight: 1.3, price: '20a', disarm: 'nem', weaponBreak: null, penetration: 'nem', stp: 8 },
    { name: 'Kahrei nyilpuska', kind: 'nyilpuska', subgroup: 'Nyilpuskak', time: 5, damage: '2k6', ke: 6, te: null, ve: null, ce: 14, rangeFeet: 100, weight: 4, price: '120a', disarm: 'nem', weaponBreak: null, penetration: 'igen', stp: 15 },
    { name: 'Vadasz szamszerij', kind: 'nyilpuska', subgroup: 'Nyilpuskak', time: 10, damage: '3k6', ke: 5, te: null, ve: null, ce: 15, rangeFeet: 150, weight: 4, price: '5a', disarm: 'nem', weaponBreak: null, penetration: 'igen', stp: 20 },
    { name: 'Nehez nyilpuska', kind: 'nyilpuska', subgroup: 'Nyilpuskak', time: '2 kör', damage: '6k6', ke: 0, te: null, ve: null, ce: 15, rangeFeet: 250, weight: 7, price: '12a', disarm: 'nem', weaponBreak: null, penetration: 'igen', stp: 30 },
    { name: 'Shadoni panceltoro', kind: 'nyilpuska', subgroup: 'Nyilpuskak', time: '4 kör', damage: '8k6', ke: 0, te: null, ve: null, ce: 20, rangeFeet: 400, weight: 20, price: '40a', disarm: 'nem', weaponBreak: null, penetration: 'igen', stp: 35 },

    // Egyeb celzofegyverek
    { name: 'Fuvocso', kind: 'celzofegyver', subgroup: 'Egyeb celzofegyverek', time: 3, damage: '1k6/2', ke: 8, te: null, ve: null, ce: 7, rangeFeet: 30, weight: 0.4, price: '6e', disarm: 'nem', weaponBreak: null, penetration: 'nem', stp: 2 },
    { name: 'Tuveto', kind: 'celzofegyver', subgroup: 'Egyeb celzofegyverek', time: 3, damage: '1k6/3', ke: 10, te: null, ve: null, ce: 2, rangeFeet: 5, weight: 0.2, price: '6e', disarm: 'nem', weaponBreak: null, penetration: 'nem', stp: 5 },
    { name: 'Parittya', kind: 'celzofegyver', subgroup: 'Egyeb celzofegyverek', time: 5, damage: '2k6', ke: 4, te: null, ve: null, ce: 6, rangeFeet: 100, weight: 0.1, price: '30r', disarm: 'nem', weaponBreak: null, penetration: 'nem', stp: 5 },
  ],
  weaponSpecialProperties: [
    { rule: 'Haritotor', description: 'Masodlagos fegyver; kifejezetten vedekezesre/haritasra optimalizalt.' },
    { rule: 'Fejvadaszkard', description: 'Masodik markolat; alkarhoz szoritva alkarvedokent es szuk helyen belharcra is jo.' },
    { rule: 'Meregfog', description: 'Markolatba epitett meregtartaly es kioldo mechanika; tobb konstrukcio, nagyon draga, ritka.' },
    { rule: 'Bola', description: 'Talalatnal guzsba fog, a celpont VE-je csokkenhet.' },
    { rule: 'Dobohalo', description: 'Ismetelt hasznalatnal TE-buntetes; csak minden 3. korben tamadhato.' },
    { rule: 'Lancos buzogany', description: 'Pajzs moge is becsaphat, mert a lanc megkeruli a kisebb pajzsokat.' },
    { rule: 'Szigony', description: 'Visszahuzhato zsineggel hasznalhato; fegyvertoresre es lefegyverzesre kulonosen alkalmas.' },
    { rule: 'Elf ij', description: 'Elo/magikus fegyver, hordozojaval szimpatikus kapcsolatban all.' },
    { rule: 'Kahrei nyilpuska', description: 'Allithato feszites; koronként 1/2/3 loves kulonbozo sebzessel es atutessel.' },
    { rule: 'Tuveto', description: 'Rejtett, mergezett, alkarra szerelt mechanikus celzofegyver; ujratoltese lassu.' },
    { rule: 'Fuvocso', description: 'Tipikusan mereg celba juttatasara, lesbol hasznalt eszkoz.' },
    { rule: 'Garott', description: 'Fojtohurok; meglepetesszeru hasznalat; koronként folyamatos sebzes.' },
    { rule: 'Vassulyom', description: 'Teruletzaro eszkoz; talpat sert, mozgast korlatoz, mergezheto.' },
  ],
  shields: [
    { name: 'Pajzs, kicsi', mgt: 0, ve: 20, coverVe: null, weight: 1 },
    { name: 'Pajzs, kozepes', mgt: -1, ve: 35, coverVe: null, weight: 3 },
    { name: 'Pajzs, nagy', mgt: -3, ve: 50, coverVe: null, weight: 6 },
    { name: 'Pajzs, paveze', mgt: null, ve: 30, coverVe: 40, weight: 6 },
    { name: 'Alkarvedo', mgt: null, ve: 15, coverVe: null, weight: 1 },
  ],
  shieldSpecialProperties: [
    { rule: 'Kicsi pajzs', description: 'Kb. fel ynevi lab atmeroju, jellemzoen kerek, mozgekony haritoeszkoz.' },
    { rule: 'Kozepes pajzs', description: 'Hosszukas forma, foleg felsotest-vedelem.' },
    { rule: 'Nagy pajzs', description: 'Embermagas, nehezvertes lovagok es szamszerijasz fedezekpajzsa.' },
    { rule: 'Paveze', description: 'Felallithato gerinces pajzs; fedezekkent kivalo, celzodobas ellen magasabb vedoertek.' },
    { rule: 'Alkarvedo', description: 'Csak akkor adja a vedelmet, ha a vedekezo kezben nincs mas fegyver vagy pajzs.' },
  ],
  armors: [
    { name: 'Fegyverkabat', mgt: 0, sfe: 1, weight: 5, price: '1e', stp: 20 },
    { name: 'Borpancel', mgt: 0, sfe: 1, weight: 8, price: '3e', stp: 20 },
    { name: 'Kemenyitett borvertezet', mgt: -2, sfe: 4, weight: 7, price: '10a', stp: 80 },
    { name: 'Gyurus vertezet', mgt: -1, sfe: 1, weight: 12, price: '2a', stp: 20 },
    { name: 'Brigandin', mgt: -2, sfe: 3, weight: 15, price: '4a', stp: 60 },
    { name: 'Lancing', mgt: -1, sfe: 2, weight: 20, price: '10a', stp: 40 },
    { name: 'Sodronying', mgt: -1, sfe: 3, weight: 20, price: '12a', stp: 60 },
    { name: 'Pikkelyvert', mgt: -2, sfe: 5, weight: 16, price: '20a', stp: 60 },
    { name: 'Lemezvertezet', mgt: -2, sfe: 2, weight: 18, price: '40a', stp: 40 },
    { name: 'Rakozott pancel', mgt: -2, sfe: 4, weight: 25, price: '100a', stp: 80 },
    { name: 'Mellvert', mgt: -3, sfe: 4, weight: 20, price: '80a', stp: 80 },
    { name: 'Felvertezet', mgt: -4, sfe: 5, weight: 30, price: '120a', stp: 100 },
    { name: 'Teljes vertezet', mgt: -5, sfe: 6, weight: 35, price: '300a', stp: 120 },
    { name: 'Gladiatorvert', mgt: -2, sfe: 4, weight: 15, price: null, stp: 80 },
    { name: 'Krani vert', mgt: -2, sfe: 4, weight: 15, price: null, stp: 80 },
    { name: 'Kardmuvesz vert', mgt: -1, sfe: 4, weight: 15, price: null, stp: 80 },
  ],
  armorSpecialProperties: [
    { rule: 'Fegyverkabat', description: 'Alapreteg sok mas vert alatt; hianya tobb vertnel SFE-csokkenest okozhat.' },
    { rule: 'Borpancel', description: 'Rugalmas, szegecselheto, alkaron suru szegecselessel haritasra is alkalmas lehet.' },
    { rule: 'Kemenyitett borvert', description: 'Olajban kifozott, merevebb, jobb vedelem, nagyobb mozgaskorlatozas.' },
    { rule: 'Gyurus vert', description: 'Anyag-alapra varrt acelgyuruk; olcsobb, de szuras ellen gyengebb.' },
    { rule: 'Brigandin', description: 'Femlemezek ket szovetrteg kozott, atfedessel; jobb vedelem, nagyobb suly.' },
    { rule: 'Lancing/Sodronying', description: 'Gyurukbol all; fegyverkabattal adja a teljes SFE-t.' },
    { rule: 'Pikkelyvert', description: 'Atfedo femlemezkek; alapruhazattal ad teljes vedelmet.' },
    { rule: 'Lemezvertezet', description: 'Szeles lemezcsikok, kevesbe testkoveto, mozgast jobban akadalyozza.' },
    { rule: 'Rakozott pancel', description: 'Testhez simulobb retegelt lemezek; jobb hatasfok, mint a sima lemezvert.' },
    { rule: 'Mellvert/Felvert/Teljes vert', description: 'Azonos elvre epulo nehezvertek, lefedettsegben kulonboznek.' },
    { rule: 'Gladiatorvert', description: 'Reszleges, mobilitasra optimalizalt osszeallitas.' },
    { rule: 'Krani vert', description: 'A gladiatorvertnel erosebb, vallvassal kiegeszitett valtozat.' },
    { rule: 'Kardmuvesz vert', description: 'Egymasra erosített femlemezkek/pikkelyek, nagy hajlekonysaggal.' },
  ],
  relatedRules: [
    { rule: 'MGT', description: 'Ugyessegbol, Gyorsasagbol, Allokepessegbol vonodik (5 ala nem csokkent).' },
    { rule: 'SFE', description: 'Sikeres tamadas Sp-jebol levonodik.' },
    { rule: 'Tulutes pancelon', description: 'A pancel STP-t veszít; minden 20 elveszített STP utan -1 SFE.' },
    { rule: 'Javitas', description: 'Kolsege aranyos az elveszített STP-vel a teljes arhoz kepest.' },
    { rule: 'Targy-STP', description: 'Anyagfuggo, tamadastipus-fuggo szorzokkal modosul.' },
  ],
}

export const getWeaponByName = (name: string) =>
  MAGUS_EQUIPMENT_DATA.weapons.find((weapon) => weapon.name === name)

export const getArmorByName = (name: string) =>
  MAGUS_EQUIPMENT_DATA.armors.find((armor) => armor.name === name)

export const getShieldByName = (name: string) =>
  MAGUS_EQUIPMENT_DATA.shields.find((shield) => shield.name === name)
